#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


echo "Starting fastapi app with debugpy support..."

echo DEBUG_PORT: ${DEBUG_PORT}
echo API_APP: ${API_APP}
echo PORT: ${PORT}

# echo "Api running! Debugpy now accepting remote attach from clients..."
# watchmedo auto-restart --recursive -p '*.py' \
#     -- python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} --wait-for-client \
#     -m uvicorn --factory ${API_APP} --host 0.0.0.0 --port ${PORT} --workers 1

echo "Api running!"
uvicorn --factory ${API_APP} --host 0.0.0.0 --port ${PORT} --workers 1
